server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/account_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

custom:
  bad_request: 400
  conflict: 409
  ok: 200
  not_found: 404

resilience4j:
  circuitbreaker:
    instances:
      sequenceService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

      userService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

      transactionService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      sequenceService:
        max-attempts: 3
        wait-duration: 200ms
      userService:
        max-attempts: 3
        wait-duration: 200ms
      transactionService:
        max-attempts: 3
        wait-duration: 200ms

  ratelimiter:
    instances:
      sequenceService:
        limit-for-period: 10
        limit-refresh-period: 1s
      userService:
        limit-for-period: 10
        limit-refresh-period: 1s
      transactionService:
        limit-for-period: 10
        limit-refresh-period: 1s
