server:
  port: 8085

spring:
  application:
    name: fund-transfer-service

  datasource:
    url: jdbc:mysql://localhost:3306/fund_transfer_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  pattern:
    level: "%5p [traceId=%X{trace_id} spanId=%X{span_id}]"

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

      transactionService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 200ms
      transactionService:
        max-attempts: 3
        wait-duration: 200ms

  ratelimiter:
    instances:
      accountService:
        limit-for-period: 10
        limit-refresh-period: 1s
      transactionService:
        limit-for-period: 10
        limit-refresh-period: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
