server:
  port: 8085

spring:
  application:
    name: fund-transfer-service

  datasource:
    url: jdbc:mysql://localhost:3306/fund_transfer_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 200ms

  ratelimiter:
    instances:
      accountService:
        limit-for-period: 10
        limit-refresh-period: 1s
        timeout-duration: 0
