spring:
  application:
    name: sequence-generator

  datasource:
    url: jdbc:mysql://localhost:3306/sequence_generator
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [traceId=%X{trace_id} spanId=%X{span_id}]"

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}
