spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://localhost:3306/transaction_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 200ms

  ratelimiter:
    instances:
      accountService:
        limit-for-period: 10
        limit-refresh-period: 1s
