spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:user_service}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  config:
    keycloak:
      server-url: http://localhost:8571
      realm: banking-service
      client-id: banking-service-api-client
      client-secret: 932OFITe8vtH4z0G9gem4Afd69JhbwrI

server:
  port: 8082

logging:
  pattern:
    level: "%5p [traceId=%X{trace_id} spanId=%X{span_id}]"

otel:
  resource:
    attributes:
      service.name: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

  retry:
    instances:
      accountService:
        max-attempts: 3
        wait-duration: 200ms

  ratelimiter:
    instances:
      accountService:
        limit-for-period: 10
        limit-refresh-period: 1s

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: ${spring.application.name}
